In [5]:
import numpy as np
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [6]:
numpy_array_from_list = np.array(myPythonList)
print(numpy_array_from_list)


[1 9 8 3]


In [7]:
a  = np.array([1,9,8,3])
print(a)


[1 9 8 3]


In [8]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [9]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [11]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [12]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [15]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [22]:
d = np.array([
    [[1, 2,3],
    [4, 5, 6]],
    [[7, 8,9],
    [10, 11, 12]]])

print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [2]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [3]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [4]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [8]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [9]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.94049737 5.48482557 4.65020522 5.47170621 4.69827256 5.56229401
 4.50658697 5.72805192 5.63558335 5.3629289 ]


In [11]:
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [13]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [15]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [17]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [18]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [19]:
## Slice
import numpy as np
e  = np.array([(4,5,6), (7,8,9)])
print(e)

[[4 5 6]
 [7 8 9]]


In [20]:
## First column
print('First row:', e[0])
## Second col
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [21]:
print('Second column:', e[:,1])

Second column: [5 8]


In [23]:
print(e[1, :2])

[7 8]


In [24]:
print(e[:2,1])

[5 8]


In [25]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.51311423 4.79102377 4.54916718 4.84343912 6.6451333  4.62876903
 4.85611821 5.40177111 5.41091619 4.54193149]


In [26]:
### Min 
print(np.min(normal_array))
### Max 
print(np.max(normal_array))
### Mean 
print(np.mean(normal_array))
### Median
print(np.median(normal_array))
### Sd
print(np.std(normal_array))

4.513114234939578
6.6451332993002366
5.018138364256927
4.817231444554087
0.625322095622746


In [27]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [28]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [29]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [30]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [31]:
#create a square matrix 
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

np.linalg.matrix_rank(mx)

3

In [33]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00  2.80575969e-16 -8.29646454e-16] [[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


In [34]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [35]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [36]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]


In [1]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
##Dimension
a.ndim

1

In [9]:
#shape
b.shape


(2, 3)

In [8]:
#Type
a.dtype

dtype('int32')

In [10]:
#Size
a.itemsize

4

In [11]:
#total size
a.nbytes

12

In [12]:
#number of elements
a.size

3

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r, c]
a[1, 5]

13

In [16]:
# Get a specific row 
p=a[0, :]
print(p)

[1 2 3 4 5 6 7]


In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get specific element (work outside in)
b[0,1,1]

4

In [22]:
b


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])